# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rotate_ui_optimflow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1306, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CAG_OG = QtWidgets.QLabel(self.centralwidget)
        self.CAG_OG.setEnabled(True)
        self.CAG_OG.setText("")
        self.CAG_OG.setObjectName("CAG_OG")
        self.horizontalLayout_2.addWidget(self.CAG_OG)
        self.CT_SIM = QtWidgets.QLabel(self.centralwidget)
        self.CT_SIM.setSizeIncrement(QtCore.QSize(0, 0))
        self.CT_SIM.setText("")
        self.CT_SIM.setObjectName("CT_SIM")
        self.horizontalLayout_2.addWidget(self.CT_SIM)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_8, 2, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 4, 1, 1)
        self.CAG_BAR = QtWidgets.QScrollBar(self.centralwidget)
        self.CAG_BAR.setOrientation(QtCore.Qt.Vertical)
        self.CAG_BAR.setObjectName("CAG_BAR")
        self.gridLayout.addWidget(self.CAG_BAR, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CAG_DEG = QtWidgets.QLabel(self.centralwidget)
        self.CAG_DEG.setObjectName("CAG_DEG")
        self.horizontalLayout_4.addWidget(self.CAG_DEG)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.ROTATE_DEG = QtWidgets.QLabel(self.centralwidget)
        self.ROTATE_DEG.setObjectName("ROTATE_DEG")
        self.horizontalLayout_4.addWidget(self.ROTATE_DEG)
        self.RESET = QtWidgets.QPushButton(self.centralwidget)
        self.RESET.setObjectName("RESET")
        self.horizontalLayout_4.addWidget(self.RESET)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LOAD_CAG = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_CAG.setObjectName("LOAD_CAG")
        self.horizontalLayout_7.addWidget(self.LOAD_CAG)
        self.LOAD_CAG_MAT = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_CAG_MAT.setObjectName("LOAD_CAG_MAT")
        self.horizontalLayout_7.addWidget(self.LOAD_CAG_MAT)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.LOAD_CT = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD_CT.setObjectName("LOAD_CT")
        self.horizontalLayout_3.addWidget(self.LOAD_CT)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RAO_LAO = QtWidgets.QScrollBar(self.centralwidget)
        self.RAO_LAO.setMinimum(-360)
        self.RAO_LAO.setMaximum(360)
        self.RAO_LAO.setOrientation(QtCore.Qt.Vertical)
        self.RAO_LAO.setObjectName("RAO_LAO")
        self.horizontalLayout_5.addWidget(self.RAO_LAO)
        self.CRA_CAU = QtWidgets.QScrollBar(self.centralwidget)
        self.CRA_CAU.setMinimum(-360)
        self.CRA_CAU.setMaximum(360)
        self.CRA_CAU.setOrientation(QtCore.Qt.Vertical)
        self.CRA_CAU.setObjectName("CRA_CAU")
        self.horizontalLayout_5.addWidget(self.CRA_CAU)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 4, 1, 1)
        self.STATE = QtWidgets.QLabel(self.centralwidget)
        self.STATE.setAlignment(QtCore.Qt.AlignCenter)
        self.STATE.setObjectName("STATE")
        self.gridLayout.addWidget(self.STATE, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SAVE_CAG = QtWidgets.QPushButton(self.centralwidget)
        self.SAVE_CAG.setObjectName("SAVE_CAG")
        self.horizontalLayout.addWidget(self.SAVE_CAG)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SAVE_CT_SK_MASK = QtWidgets.QPushButton(self.centralwidget)
        self.SAVE_CT_SK_MASK.setObjectName("SAVE_CT_SK_MASK")
        self.horizontalLayout_6.addWidget(self.SAVE_CT_SK_MASK)
        self.SAVE_CT = QtWidgets.QPushButton(self.centralwidget)
        self.SAVE_CT.setObjectName("SAVE_CT")
        self.horizontalLayout_6.addWidget(self.SAVE_CT)
        self.CT_VOLUME_SAVE = QtWidgets.QPushButton(self.centralwidget)
        self.CT_VOLUME_SAVE.setObjectName("CT_VOLUME_SAVE")
        self.horizontalLayout_6.addWidget(self.CT_VOLUME_SAVE)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.CAG_frame = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CAG_frame.sizePolicy().hasHeightForWidth())
        self.CAG_frame.setSizePolicy(sizePolicy)
        self.CAG_frame.setObjectName("CAG_frame")
        self.gridLayout.addWidget(self.CAG_frame, 5, 1, 1, 1)
        self.OP_FLOW = QtWidgets.QCheckBox(self.centralwidget)
        self.OP_FLOW.setEnabled(True)
        self.OP_FLOW.setObjectName("OP_FLOW")
        self.gridLayout.addWidget(self.OP_FLOW, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RAO_LAO_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAO_LAO_input.sizePolicy().hasHeightForWidth())
        self.RAO_LAO_input.setSizePolicy(sizePolicy)
        self.RAO_LAO_input.setObjectName("RAO_LAO_input")
        self.horizontalLayout_8.addWidget(self.RAO_LAO_input)
        self.CRA_CAU_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CRA_CAU_input.sizePolicy().hasHeightForWidth())
        self.CRA_CAU_input.setSizePolicy(sizePolicy)
        self.CRA_CAU_input.setObjectName("CRA_CAU_input")
        self.horizontalLayout_8.addWidget(self.CRA_CAU_input)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RAO/LAO"))
        self.label_2.setText(_translate("MainWindow", "CRA/CAU"))
        self.CAG_DEG.setText(_translate("MainWindow", "RAO/LAO:  CRA/CAU:  "))
        self.ROTATE_DEG.setText(_translate("MainWindow", "RAO/LAO:  CRACAU:  "))
        self.RESET.setText(_translate("MainWindow", "Reset"))
        self.LOAD_CAG.setText(_translate("MainWindow", "Load CAG dicom"))
        self.LOAD_CAG_MAT.setText(_translate("MainWindow", "Load CAG mat"))
        self.LOAD_CT.setText(_translate("MainWindow", "Load CT"))
        self.STATE.setText(_translate("MainWindow", "State"))
        self.SAVE_CAG.setText(_translate("MainWindow", "Save CAG"))
        self.SAVE_CT_SK_MASK.setText(_translate("MainWindow", "Save CT sk Mask"))
        self.SAVE_CT.setText(_translate("MainWindow", "Save CT projection"))
        self.CT_VOLUME_SAVE.setText(_translate("MainWindow", "Save CT volume"))
        self.CAG_frame.setText(_translate("MainWindow", "0"))
        self.OP_FLOW.setText(_translate("MainWindow", "OpimtFlow"))
        self.RAO_LAO_input.setText(_translate("MainWindow", "0"))
        self.CRA_CAU_input.setText(_translate("MainWindow", "0"))


